name: pharmako
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

# ----------------- PACKAGES ---------------#

dependencies:
  flutter:
    sdk: flutter

  # ------- Utility Packages -----------

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  google_fonts:
  image_picker: ^1.0.4
  cached_network_image: ^3.3.1
  intl_phone_field: ^3.2.0

  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.0

  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  uuid: ^4.0.0
  flutter_markdown: ^0.7.4+3
  flutter_native_splash: ^2.3.2
  flutter_paystack: ^1.0.7

  # --------- utility Packages ------
  #  http: ^1.1.0
  http: ^0.13.0
  intl: ^0.17.0
  logger: ^2.0.1
  lottie: ^3.0.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.12
  connectivity_plus: ^6.1.1
  carousel_slider: ^5.0.0
  clipboard: ^0.1.3
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.69.2

  # -------- state management --------
  get: ^4.6.5
  get_storage: ^2.1.1

  # ----------------- END OF PACKAGES ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # -------------- Local Assets --------------- #
  # assets:
  #   - images/
  #   - icons/

  # -------------- Local Fonts --------------- #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
